<div class="space-y-6">
    <!-- Page Header -->
    <div>
        <h2 class="text-3xl font-bold text-gray-900">Tableau de Bord</h2>
        <p class="text-gray-600 mt-2">Bienvenue sur EduTrack - Votre plateforme de suivi d'apprenants</p>
    </div>

    <!-- Stats Cards -->
    <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
        <x-card class="bg-gradient-to-br from-blue-50 to-blue-100 border border-blue-200">
            <div class="flex items-center justify-between">
                <div>
                    <p class="text-gray-600 text-sm font-medium">Total Apprenants</p>
                    <p class="text-3xl font-bold text-blue-600 mt-2" id="total-learners">0</p>
                </div>
                <div class="w-12 h-12 bg-blue-600 rounded-lg flex items-center justify-center">
                    <svg class="w-6 h-6 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 4.354a4 4 0 110 5.292M15 21H3v-2a6 6 0 0112 0v2zm0 0h6v-2a6 6 0 00-9-5.197M13 7a4 4 0 11-8 0 4 4 0 018 0z"></path>
                    </svg>
                </div>
            </div>
        </x-card>

        <x-card class="bg-gradient-to-br from-green-50 to-green-100 border border-green-200">
            <div class="flex items-center justify-between">
                <div>
                    <p class="text-gray-600 text-sm font-medium">Cours Actifs</p>
                    <p class="text-3xl font-bold text-green-600 mt-2" id="active-courses">0</p>
                </div>
                <div class="w-12 h-12 bg-green-600 rounded-lg flex items-center justify-center">
                    <svg class="w-6 h-6 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 6.253v13m0-13C6.5 6.253 2 10.998 2 17s4.5 10.747 10 10.747c5.5 0 10-4.998 10-10.747S17.5 6.253 12 6.253z"></path>
                    </svg>
                </div>
            </div>
        </x-card>

        <x-card class="bg-gradient-to-br from-purple-50 to-purple-100 border border-purple-200">
            <div class="flex items-center justify-between">
                <div>
                    <p class="text-gray-600 text-sm font-medium">Taux de Complétion</p>
                    <p class="text-3xl font-bold text-purple-600 mt-2" id="completion-rate">0%</p>
                </div>
                <div class="w-12 h-12 bg-purple-600 rounded-lg flex items-center justify-center">
                    <svg class="w-6 h-6 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z"></path>
                    </svg>
                </div>
            </div>
        </x-card>

        <x-card class="bg-gradient-to-br from-orange-50 to-orange-100 border border-orange-200">
            <div class="flex items-center justify-between">
                <div>
                    <p class="text-gray-600 text-sm font-medium">Activité Aujourd'hui</p>
                    <p class="text-3xl font-bold text-orange-600 mt-2" id="today-activity">0</p>
                </div>
                <div class="w-12 h-12 bg-orange-600 rounded-lg flex items-center justify-center">
                    <svg class="w-6 h-6 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 10V3L4 14h7v7l9-11h-7z"></path>
                    </svg>
                </div>
            </div>
        </x-card>
    </div>

    <!-- Charts Section -->
    <div class="grid grid-cols-1 lg:grid-cols-2 gap-6">
        <x-card title="Progression Hebdomadaire" class="lg:col-span-1">
            <div class="h-64 flex items-end justify-around gap-2 p-4">
                <div id="chart-container" class="w-full h-full flex items-end justify-around gap-2">
                    <!-- Chart bars will be generated by JavaScript -->
                </div>
            </div>
        </x-card>

        <x-card title="Apprenants Récents" class="lg:col-span-1">
            <div id="recent-learners" class="space-y-3">
                <!-- Recent learners will be populated by JavaScript -->
            </div>
        </x-card>
    </div>

    <!-- Quick Actions -->
    <x-card title="Actions Rapides">
        <div class="flex flex-wrap gap-3">
            <x-button variant="primary" data-action="add-learner">
                <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 4v16m8-8H4"></path>
                </svg>
                Ajouter un Apprenant
            </x-button>

            <x-button variant="secondary" data-action="add-course">
                <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 4v16m8-8H4"></path>
                </svg>
                Créer un Cours
            </x-button>

            <x-button variant="ghost" data-action="export-report">
                <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4"></path>
                </svg>
                Exporter le Rapport
            </x-button>
        </div>
    </x-card>
</div>
